# Generated by Django 4.2.11 on 2026-04-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='ledger.merchant')),
            ],
            options={
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['key'], name='idempotency_key_0fd07b_idx'), models.Index(fields=['merchant', 'key'], name='idempotency_merchan_16ab98_idx'), models.Index(fields=['expires_at'], name='idempotency_expires_6c9d28_idx')],
                'unique_together': {('merchant', 'key')},
            },
        ),
    ]
